databases:
  - name: todo_list
    databaseName: todo_list_production
    user: todo_api
    plan: free

services:
  - type: web
    name: todo-api
    runtime: ruby
    plan: free
    buildCommand: "bundle install --without development test"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server -p 3000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_list_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
